### ISSUE TITLE
`bidsstats` not defined

### ISSUE THREAD

**Issue by neuromechanist** [sccn/EEG-BIDS#221]
I am trying to export the processed HBN Release 3 using the new (and the old) EEG-BIDS and I get the following error:
`bids_export error: undefined argument 'bidsstats'`

This error occurs in `bids_export` line 327.

**Comment by arnodelorme** [comment]
Let me look into that.

**Comment by arnodelorme** [comment]
I think you might not be using the latest version. Line 327 does not have 'bidsstats'. In fact there is no mention of 'bidsstats' in the file. Let me know.

https://github.com/sccn/EEG-BIDS/blob/64ed249d2a315849b9ec0e5c84df0aa0f397bd64/bids_export.m#L327

**Comment by neuromechanist** [comment]
I used the EEG-BIDS from the EEGLAB plug-in browser. Line 327 reads:
```matlab
if isstr(opt), error(opt); end
```

I need to keep the pipeline limited to stable releases to ensure reproducibility.

Yes, there is no `bidsstats` option, which makes me wonder if this argument is coming from the upstream functions. I will take a look.

**Comment by arnodelorme** [comment]
The best version of this plugin is the dev version. When your pipeline is stable, we can issue a new release of the plugin which you can reference in the paper.

**Comment by neuromechanist** [comment]
Ok, I found the culprit:
`pop_importbids` adds `bidsstats` to the `EEG.BIDS` structure. Since this field is not recognized by `bids_export`, it throws an error when you want to re-export a BIDS dataset (i.e., importing a dataset in STUDY, process and export the STUDY as a new BIDS dataset)

Also, EEG-BIDS does not seem to have a dev branch, so I am sticking with the master branch anyway.

I removed the field for my use case and exported the BIDS successfully.

**Comment by neuromechanist** [comment]
I think `bidsstats` should be added as a condition to this line on `pop_exportbids` to be excluded together with the `behavioral` when `bids_export` is called:
https://github.com/sccn/EEG-BIDS/blob/eb7319fc2f59f403a8eb2e0ecf550355a343298d/pop_exportbids.m#L141

`bids_export` itself does not deal with `EEG.BIDS` explicitly. but rather get the inputs as `varargin` from upstream (in this case `pop_exportbids`)

**Comment by arnodelorme** [comment]
Can you do a quick pull request?
